@server = http://localhost:3000

# 책 목록 조회
GET {{server}}/books

### 책 생성
POST {{server}}/books
Content-Type: application/json

{
    "title": "아이디어 불패의 법칙",              
    "author": "알베르토 사보이아",               
    "isAvailable": true           
}

### 특정 책 조회
GET {{server}}/books/{bookId}

### 책 삭제
DELETE {{server}}/books/{bookId}

### 책 정보 수정
PUT {{server}}/books/{bookId}
Content-Type: application/json

{
    "title": "타이틀 수정",          
    "author": "next.kim",            
    "isAvailable": false            
}
